[tool.poetry]
name = "cookiecutter-tornado"
version = "0.3.0"
description = "Cookiecutter template for Tornado based projects"
authors = ["Henning Kage <henning.kage@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
bumpversion = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest-cookies = "^0.4.0"
pytest = "<5.0.0"
cookiecutter = "<=1.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
