# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "{{ cookiecutter.package_name }}"
  config.vm.box = "maier/alpine-3.8-x86_64"
  config.vm.box_version = '3.8.1'
  config.vm.network :forwarded_port, guest: 8000, host: 8000, id: "{{ cookiecutter.package_name }}"
  config.vm.synced_folder ".", "/home/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 256
    vb.cpus = 1
  end
  config.vm.provision :shell, :path => "bootstrap.sh"
end
